"""add service sessions

Revision ID: 169b911af90c
Revises: 85baa527605a
Create Date: 2026-09-18 17:43:53.718489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169b911af90c'
down_revision: Union[str, Sequence[str], None] = '85baa527605a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue_entry_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['queue_entry_id'], ['queue_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_sessions')
    # ### end Alembic commands ###
