"""add service relationship to queues

Revision ID: 9ef98e59c61f
Revises: 69cf7895c15b
Create Date: 2026-09-17 23:13:01.053220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef98e59c61f'
down_revision: Union[str, Sequence[str], None] = '69cf7895c15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queues', sa.Column('service_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'queues', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'queues', type_='foreignkey')
    op.drop_column('queues', 'service_id')
    # ### end Alembic commands ###
