"""add queue entry relationship

Revision ID: def75cbf4b5f
Revises: 86d78c6a8401
Create Date: 2026-09-16 23:56:04.455280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def75cbf4b5f'
down_revision: Union[str, Sequence[str], None] = '86d78c6a8401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'queue_entries', 'queues', ['queue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'queue_entries', type_='foreignkey')
    # ### end Alembic commands ###
